zuul:
  routes:
    userapi:
      id: /user/**
      service-id: USER-SERVICE
#    useraataapi:
#      path: /userdata/**
#      serviceId: USER-DATA-SERVICE
    zipkinclientapi:
      id: /zipkinclient/**
      service-id: zipkin-client
  prefix: /v1
