info:
  app: gateway
  version: v1.0.0
server:
  port: 24080
spring:
  application:
    name: gateway

  # sleuth zipkin
  sleuth:
    sampler:
      probability: 0.1
  zipkin:
    base-url: http://ZIPKIN-SERVICE
    discovery-client-enabled: true
