info:
  app: user-service
  version: v1.0.0
server:
  port: 22080
spring:
  application:
    name: user-service

feign:
  hystrix:
    enabled: true

##暴露actuator的所有端口
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS